// Code generated by fieldctl; DO NOT EDIT.
package models

type PostCF struct {
	AuthorEmail string `cf:"author_email" validate:"email" json:"author_email"`
	Rating      *int   `cf:"rating" validate:"number" json:"rating,omitempty"`
}
