DROP TABLE IF EXISTS authz.casbin_rule;
DROP SCHEMA IF EXISTS authz;
DROP TABLE IF EXISTS gcfm_role_policies;
DROP TABLE IF EXISTS gcfm_user_roles;
DROP TABLE IF EXISTS gcfm_roles;
DROP TABLE IF EXISTS gcfm_users;
DROP TABLE IF EXISTS gcfm_audit_logs;
DROP TABLE IF EXISTS gcfm_events_failed;
DROP TABLE IF EXISTS gcfm_registry_snapshots;
DROP TABLE IF EXISTS gcfm_custom_fields;
DROP TABLE IF EXISTS gcfm_monitored_databases;
DROP TABLE IF EXISTS gcfm_target_labels;
DROP TABLE IF EXISTS gcfm_targets;
DROP TABLE IF EXISTS gcfm_target_config_version;
DROP TABLE IF EXISTS gcfm_registry_schema_version;
DROP TRIGGER IF EXISTS gcfm_widgets_notify_iud ON gcfm_widgets;
DROP FUNCTION IF EXISTS notify_widgets_changed();
DROP TABLE IF EXISTS gcfm_widgets;
