DELETE FROM gcfm_role_policies p USING gcfm_roles r WHERE p.role_id=r.id AND r.name='admin' AND p.path='/v1/snapshots' AND p.method='GET';
DELETE FROM gcfm_role_policies p USING gcfm_roles r WHERE p.role_id=r.id AND r.name='admin' AND p.path='/v1/snapshots' AND p.method='POST';
DELETE FROM gcfm_role_policies p USING gcfm_roles r WHERE p.role_id=r.id AND r.name='admin' AND p.path='/v1/snapshots/{ver}/apply' AND p.method='POST';
DELETE FROM gcfm_role_policies p USING gcfm_roles r WHERE p.role_id=r.id AND r.name='admin' AND p.path='/v1/databases' AND p.method='GET';
DELETE FROM gcfm_role_policies p USING gcfm_roles r WHERE p.role_id=r.id AND r.name='admin' AND p.path='/v1/databases' AND p.method='POST';
DELETE FROM gcfm_role_policies p USING gcfm_roles r WHERE p.role_id=r.id AND r.name='editor' AND p.path='/v1/snapshots' AND p.method='GET';
DELETE FROM gcfm_role_policies p USING gcfm_roles r WHERE p.role_id=r.id AND r.name='editor' AND p.path='/v1/databases' AND p.method='GET';
DELETE FROM gcfm_role_policies p USING gcfm_roles r WHERE p.role_id=r.id AND r.name='viewer' AND p.path='/v1/databases' AND p.method='GET';
DELETE FROM gcfm_role_policies p USING gcfm_roles r WHERE p.role_id=r.id AND r.name='editor' AND p.path='/v1/metadata/tables' AND p.method='GET';
DELETE FROM gcfm_role_policies p USING gcfm_roles r WHERE p.role_id=r.id AND r.name='viewer' AND p.path='/v1/metadata/tables' AND p.method='GET';
DELETE FROM gcfm_role_policies p USING gcfm_roles r WHERE p.role_id=r.id AND r.name='editor' AND p.path='/v1/databases/{id}/scan' AND p.method='POST';
DELETE FROM gcfm_registry_schema_version WHERE version=17;
