package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

func newPluginImportCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "plugin-import [module]",
		Short: "Generate static plugin import",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			module := args[0]
			fmt.Fprintf(cmd.OutOrStdout(), "// Code generated by fieldctl; DO NOT EDIT.\npackage main\nimport _ \"%s\"\n", module)
			return nil
		},
	}
	return cmd
}
