---
name: CF Schema Diff
'on':
  pull_request:
    paths: ["registry.yaml", "**/*.go", "internal/**"]
jobs:
  diff:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: app
        ports:
          - "5432:5432"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go build -o fieldctl ./cmd/fieldctl
      - run: ./fieldctl db migrate --db $DB_DSN --schema public
        env:
          DB_DSN: postgres://postgres:pass@localhost:5432/app?sslmode=disable
      - id: diff
        run: |
          ./fieldctl diff --db $DB_DSN --schema public --file registry.yaml \
            --fail-on-change >diff.txt || \
            echo "changed=true" >> "$GITHUB_OUTPUT"
        env:
          DB_DSN: postgres://postgres:pass@localhost:5432/app?sslmode=disable
      - if: steps.diff.outputs.changed == 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "Custom-Field Schema Diff"
          path: diff.txt
      - if: steps.diff.outputs.changed == 'true'
        run: exit 1
