---
name: CF Schema Drift

'on':
  pull_request:
    paths:
      - "registry.yaml"
      - "**/*.go"
      - "internal/**"
      - "migrations/**"

jobs:
  diff:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: app
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_DSN: postgres://postgres:pass@localhost:5432/app?sslmode=disable

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install fieldctl
        run: |
          go install github.com/faciam-dev/fieldctl/cmd/fieldctl@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - name: Wait for DB
        run: scripts/ci/wait-for-db.sh
        shell: bash
      - name: Migrate DB
        run: fieldctl db migrate --db "$DB_DSN" --schema public --seed
      - name: Schema diff
        id: diff
        run: |
          set +e
          fieldctl diff \
            --db "$DB_DSN" \
            --schema public \
            --file registry.yaml \
            --format markdown \
            --fail-on-change > diff.txt
          exit_code=$?
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
          if [ $exit_code -eq 2 ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
          [ -s diff.txt ] || echo "✅ No schema drift detected." > diff.txt
          exit 0
      - if: steps.diff.outputs.changed == 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Custom-Field Schema Diff
          path: diff.txt
      - if: steps.diff.outputs.changed == 'true'
        run: exit 1
