---
name: CF Schema Diff
'on':
  pull_request:
    paths: ["registry.yaml", "**/*.go", "internal/**"]
jobs:
  diff:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: app
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Clean Go module cache
        run: go clean -modcache
      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U postgres && exit 0
            sleep 2
          done
          echo "Postgres not ready" && exit 1
        env:
          PGPASSWORD: pass
      - name: Install fieldctl
        run: |
          go install ./cmd/fieldctl
          echo "${GOBIN:-$(go env GOPATH)/bin}" >> "$GITHUB_PATH"
      - name: Migrate DB (registry + user tables)
        run: |
          fieldctl db migrate \
            --db "$DB_DSN" \
            --schema public \
            --driver postgres \
            --seed
        env:
          DB_DSN: postgres://postgres:pass@localhost:5432/app?sslmode=disable
      - run: |
          fieldctl apply \
            --db $DB_DSN \
            --schema public \
            --driver postgres \
            --file registry.yaml
        env:
          DB_DSN: postgres://postgres:pass@localhost:5432/app?sslmode=disable
      - id: diff
        run: |
          fieldctl diff \
            --db "$DB_DSN" \
            --schema public \
            --file registry.yaml \
            --format markdown --fail-on-change > diff.txt
          exit_code=$?
          echo "exit_code=$exit_code" >> "$GITHUB_OUTPUT"
          if [ $exit_code -eq 2 ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
          [ -f diff.txt ] || echo "diff command failed" > diff.txt
        env:
          DB_DSN: postgres://postgres:pass@localhost:5432/app?sslmode=disable
      - if: steps.diff.outputs.changed == 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "Custom-Field Schema Diff"
          path: ./diff.txt
      - if: steps.diff.outputs.changed == 'true'
        run: exit 1
