---
name: CI

'on':
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports: [ "5432:5432" ]
        env:
          POSTGRES_DB: gcfm_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/gcfm_test?sslmode=disable
    steps:
      - uses: actions/checkout@v4
      - name: Clean Go caches
        run: |
          rm -rf ~/go/pkg/mod
          rm -rf ~/.cache/go-build
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - run: gofmt -w $(git ls-files '*.go') && git diff --exit-code
      - name: Run tests
        run: go test ./...
      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          strict: true
