---
name: CI

'on':
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Clean Go caches
        run: |
          rm -rf ~/go/pkg/mod
          rm -rf ~/.cache/go-build
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - run: gofmt -w $(git ls-files '*.go') && git diff --exit-code
      - name: Run tests
        run: go test ./...
      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          strict: true
